name: appsyncmasterclass
schema: schema.graphql

authentication:
  type: AMAZON_COGNITO_USER_POOLS
  config:
    awsRegion: us-east-1
    defaultAction: ALLOW
    userPoolId: !Ref CognitoUserPool

dataSources:
  usersTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref UsersTable
  
  tweetsTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TweetsTable

  timelinesTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TimelinesTable
  
  likesTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref LikesTable

  LikesDataSources:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: 
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn
    
  getImageUploadUrlFn:
    type: AWS_LAMBDA
    config:
      functionName: getImageUploadUrl
  
  tweetFn:
    type: AWS_LAMBDA
    config:
      functionName: tweet
  
pipelineFunctions:
  getMyTimelineByUser:
    dataSource: timelinesTable
    code: mapping-templates/queries/getMyTimelineByUser.js
  
  getTweetsByTimeline:
    dataSource: tweetsTable
    code: mapping-templates/queries/getTweetsByTimeline.js

resolvers:
# Query Resolvers
  Query.getMyProfile:
    kind: UNIT
    field: getMyProfile
    dataSource: usersTable
    request: mapping-templates/queries/getMyProfile.request.vtl
    response: mapping-templates/queries/getMyProfile.response.vtl
  
  Query.getImageUploadUrl:
    kind: UNIT
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFn

  Query.getTweets:
    functions:
      - dataSource: tweetsTable
        code: mapping-templates/queries/getTweets.js

  Query.getMyTimeLine:
    functions:
      - getMyTimelineByUser
      - getTweetsByTimeline

# Mutation Resolvers
  Mutation.tweet:
    kind: UNIT
    field: tweet
    dataSource: tweetFn

  Mutation.editMyProfile:
    kind: UNIT
    field: editMyProfile
    dataSource: usersTable
    request: mapping-templates/mutations/editMyProfile.request.vtl
    response: mapping-templates/mutations/editMyProfile.response.vtl
  
  Mutation.like:
    functions:
      - code: mapping-templates/mutations/createLike.js
        dataSource: LikesDataSources

# Nested Fields
  Tweet.profile:
    functions:
      - dataSource: usersTable
        code: mapping-templates/queries/tweet.profile.js

  Tweet.liked:
    functions:
      - dataSource: likesTable
        code: mapping-templates/queries/tweet.liked.js

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable