name: appsyncmasterclass
schema: schema.graphql

authentication:
  type: AMAZON_COGNITO_USER_POOLS
  config:
    awsRegion: us-east-1
    defaultAction: ALLOW
    userPoolId: !Ref CognitoUserPool

dataSources:
  tweeterTable:
    type: AMAZON_DYNAMODB
    config:
      tableName: !Ref TweeterTable

  getImageUploadUrlFn:
    type: AWS_LAMBDA
    config:
      functionName: getImageUploadUrl

resolvers:
  Query.getMyProfile:
    functions:
      - dataSource: tweeterTable
        code: resolvers/queries/getMyProfile.js

  Query.getTweets:
    functions:
      - dataSource: tweeterTable
        code: resolvers/queries/getTweetsForUser.js
  
  Query.getLikes:
    functions:
      - dataSource: tweeterTable
        code: resolvers/queries/getLikes.js

  Retweet.retweetOf:
    functions:
      - dataSource: tweeterTable
        code: resolvers/queries/getRetweet.js

  Tweet.profile:
    functions:
      - dataSource: tweeterTable
        code: resolvers/queries/getProfile.js

  Like.tweet:
    functions:
      - dataSource: tweeterTable
        code: resolvers/queries/getTweetById.js

  Mutation.createTweet:
    functions:
      - dataSource: tweeterTable
        code: resolvers/mutations/createTweet.js

  Mutation.retweet:
    functions:
      - dataSource: tweeterTable
        code: resolvers/mutations/createRetweet.js

  Mutation.like: 
    functions:
      - dataSource: tweeterTable
        code: resolvers/mutations/createLike.js

substitutions:
  TweeterTable: !Ref TweeterTable
